void api_putchar(int c);
void api_end(void);
void api_putstring_toend(char *string);
int api_create_window(char *buffer, int length, int width, int color_luc, char *title);
void api_putstring_onwindow(int window, int x, int y, int color, int length, char *string);
void api_drawrectangle_onwindow(int window, int x, int y, int length, int width, int color);
void api_initmalloc(void);	
char *api_malloc(int size);
void api_free(char *addr, int size);
void api_drawpoint(int window, int x, int y, int color);
void api_refreshwindow(int window, int x0, int y0, int x1, int y1);
void api_drawline(int window, int x0, int y0, int x1, int y1, int color);
void api_closewindow(int window);
int api_get_fifodata(int mode);
int api_alloctimer(void);
void api_inittimer(int timer, int data);
void api_settimer(int timer, int time);
void api_freetimer(int timer);
void api_beep(int tone);